export let array=[
    {
      "Posted On": "2022-05-18",
      "BHK": 2,
      "Rent": 10000,
      "Size": 1100,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Bandel",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-13",
      "BHK": 2,
      "Rent": 20000,
      "Size": 800,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Phool Bagan, Kankurgachi",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-16",
      "BHK": 2,
      "Rent": 17000,
      "Size": 1000,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Salt Lake City Sector 2",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-04",
      "BHK": 2,
      "Rent": 10000,
      "Size": 800,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Dumdum Park",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-09",
      "BHK": 2,
      "Rent": 7500,
      "Size": 850,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "South Dum Dum",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-29",
      "BHK": 2,
      "Rent": 7000,
      "Size": 600,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Thakurpukur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-21",
      "BHK": 2,
      "Rent": 10000,
      "Size": 700,
      "Floor": "Ground out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Malancha",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-21",
      "BHK": 1,
      "Rent": 5000,
      "Size": 250,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Malancha",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-07",
      "BHK": 2,
      "Rent": 26000,
      "Size": 800,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Palm Avenue Kolkata, Ballygunge",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-20",
      "BHK": 2,
      "Rent": 10000,
      "Size": 1000,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Natunhat",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-23",
      "BHK": 3,
      "Rent": 25000,
      "Size": 1200,
      "Floor": "1 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Action Area 1, Rajarhat Newtown",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-07",
      "BHK": 1,
      "Rent": 5000,
      "Size": 400,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 1,
      "Rent": 6500,
      "Size": 250,
      "Floor": "1 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Tarulia, Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-09",
      "BHK": 1,
      "Rent": 5500,
      "Size": 375,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Dum Dum Metro",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-05",
      "BHK": 3,
      "Rent": 8500,
      "Size": 900,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Paschim Barisha",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-01",
      "BHK": 3,
      "Rent": 40000,
      "Size": 1286,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "New Town Action Area 1",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-17",
      "BHK": 2,
      "Rent": 6000,
      "Size": 600,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Barasat",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-20",
      "BHK": 2,
      "Rent": 10000,
      "Size": 800,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-09",
      "BHK": 2,
      "Rent": 11000,
      "Size": 2000,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Behala Chowrasta",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-09",
      "BHK": 2,
      "Rent": 6000,
      "Size": 660,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 2,
      "Rent": 7900,
      "Size": 650,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Santoshpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-14",
      "BHK": 2,
      "Rent": 9000,
      "Size": 400,
      "Floor": "2 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Garia Station, Garia",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-15",
      "BHK": 1,
      "Rent": 4000,
      "Size": 300,
      "Floor": "Ground out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Garia Station, Garia",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-15",
      "BHK": 3,
      "Rent": 6500,
      "Size": 1600,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Joka",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-28",
      "BHK": 1,
      "Rent": 8000,
      "Size": 400,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Sreebhumi",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-22",
      "BHK": 2,
      "Rent": 7000,
      "Size": 1000,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Rajarhat",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-18",
      "BHK": 1,
      "Rent": 5300,
      "Size": 355,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Dum Dum",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-25",
      "BHK": 2,
      "Rent": 6000,
      "Size": 1000,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Kodalia, Hooghly-Chinsurah",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-22",
      "BHK": 2,
      "Rent": 8500,
      "Size": 800,
      "Floor": "4 out of 5",
      "Area Type": "Super Area",
      "Area Locality": "Baguiati",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-25",
      "BHK": 2,
      "Rent": 12500,
      "Size": 850,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Rabindra Sarobar Area, Dhakuria",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-21",
      "BHK": 1,
      "Rent": 7500,
      "Size": 350,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Baghajatin",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 2,
      "Rent": 15000,
      "Size": 900,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Project Kaikhali, Vip Road",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-16",
      "BHK": 2,
      "Rent": 6000,
      "Size": 550,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Vip Road",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-29",
      "BHK": 2,
      "Rent": 5000,
      "Size": 500,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Baruipur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 3,
      "Rent": 22000,
      "Size": 1100,
      "Floor": "2 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Dumdum Park",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-12",
      "BHK": 2,
      "Rent": 15000,
      "Size": 850,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Sreebhumi",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-03",
      "BHK": 2,
      "Rent": 12500,
      "Size": 800,
      "Floor": "2 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Shyam Bazar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-31",
      "BHK": 2,
      "Rent": 7000,
      "Size": 630,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Birati",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-10",
      "BHK": 2,
      "Rent": 21000,
      "Size": 900,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Bansdroni",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-24",
      "BHK": 1,
      "Rent": 10000,
      "Size": 270,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Jadavpur University",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-29",
      "BHK": 2,
      "Rent": 7200,
      "Size": 630,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Birati",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-12",
      "BHK": 3,
      "Rent": 12000,
      "Size": 1500,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Bhadrakali",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 1,
      "Rent": 5000,
      "Size": 600,
      "Floor": "2 out of 5",
      "Area Type": "Super Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-30",
      "BHK": 2,
      "Rent": 8500,
      "Size": 700,
      "Floor": "4 out of 14",
      "Area Type": "Carpet Area",
      "Area Locality": "Baruipur",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-27",
      "BHK": 1,
      "Rent": 6000,
      "Size": 300,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Ballygunge",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-06",
      "BHK": 2,
      "Rent": 10000,
      "Size": 1300,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Kalikapur",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-20",
      "BHK": 2,
      "Rent": 4600,
      "Size": 400,
      "Floor": "3 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 2,
      "Rent": 12000,
      "Size": 650,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Baishnabghata Patuli Township, Patuli",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-26",
      "BHK": 3,
      "Rent": 30000,
      "Size": 2000,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-12",
      "BHK": 3,
      "Rent": 15000,
      "Size": 1068,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Bansdroni",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-22",
      "BHK": 1,
      "Rent": 7500,
      "Size": 150,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Salt Lake City",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-25",
      "BHK": 1,
      "Rent": 7500,
      "Size": 450,
      "Floor": "2 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "New Town",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-03",
      "BHK": 2,
      "Rent": 5000,
      "Size": 800,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Baruipur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-23",
      "BHK": 2,
      "Rent": 15000,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Bansdroni",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 2,
      "Rent": 11000,
      "Size": 900,
      "Floor": "5 out of 5",
      "Area Type": "Super Area",
      "Area Locality": "Pancha Sayar",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-27",
      "BHK": 1,
      "Rent": 7000,
      "Size": 600,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-19",
      "BHK": 2,
      "Rent": 6000,
      "Size": 1200,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Hooghly-Chinsurah",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-19",
      "BHK": 2,
      "Rent": 6000,
      "Size": 1200,
      "Floor": "2 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Hooghly-Chinsurah",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 2,
      "Rent": 7000,
      "Size": 650,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Amtala, Diamond Harbour Road",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-06",
      "BHK": 2,
      "Rent": 8500,
      "Size": 720,
      "Floor": "4 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Shrachi Village, Madhyam Gram",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 1,
      "Rent": 5000,
      "Size": 300,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Kasba",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-21",
      "BHK": 3,
      "Rent": 30000,
      "Size": 1200,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "VIP Road Haldiram",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 3,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-04",
      "BHK": 2,
      "Rent": 10000,
      "Size": 700,
      "Floor": "7 out of 8",
      "Area Type": "Carpet Area",
      "Area Locality": "Sarsuna",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-24",
      "BHK": 3,
      "Rent": 30000,
      "Size": 2000,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Naihati",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 1,
      "Rent": 3500,
      "Size": 250,
      "Floor": "Ground out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Baksara",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 2,
      "Rent": 8000,
      "Size": 1100,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Naihati",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 1,
      "Rent": 5000,
      "Size": 300,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Kasba",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-05",
      "BHK": 2,
      "Rent": 7500,
      "Size": 600,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Amtala, Diamond Harbour Road",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-18",
      "BHK": 2,
      "Rent": 6500,
      "Size": 800,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Chak Thakurani, Thakurpukur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-07",
      "BHK": 1,
      "Rent": 7500,
      "Size": 680,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Jadavpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-07",
      "BHK": 1,
      "Rent": 7500,
      "Size": 680,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Jadavpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 2,
      "Rent": 16000,
      "Size": 850,
      "Floor": "1 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 2,
      "Rent": 16000,
      "Size": 850,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-30",
      "BHK": 2,
      "Rent": 6500,
      "Size": 700,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Bandel",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-22",
      "BHK": 3,
      "Rent": 40000,
      "Size": 1500,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Beliaghata",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-18",
      "BHK": 2,
      "Rent": 12500,
      "Size": 950,
      "Floor": "1 out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Magnolia Prestige, Rajarhat",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-08",
      "BHK": 2,
      "Rent": 5500,
      "Size": 500,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Baishnabghata Patuli Township, Patuli",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-25",
      "BHK": 1,
      "Rent": 5000,
      "Size": 450,
      "Floor": "2 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Dum Dum Heights, Jessore Road",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-03",
      "BHK": 2,
      "Rent": 6500,
      "Size": 700,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Sonarpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-12",
      "BHK": 1,
      "Rent": 8000,
      "Size": 500,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Lake Town",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-01",
      "BHK": 3,
      "Rent": 14500,
      "Size": 1800,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Belghoria",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-23",
      "BHK": 1,
      "Rent": 8200,
      "Size": 500,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Rabindra Pally, Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-23",
      "BHK": 2,
      "Rent": 15000,
      "Size": 480,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "shukhobrishti",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-21",
      "BHK": 6,
      "Rent": 20000,
      "Size": 1000,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Sonarpur",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-22",
      "BHK": 2,
      "Rent": 6700,
      "Size": 800,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Baishnavghata patuli , house number s-300 Kolkata 700094",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-27",
      "BHK": 1,
      "Rent": 10000,
      "Size": 435,
      "Floor": "2 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Kasba",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-07",
      "BHK": 2,
      "Rent": 7000,
      "Size": 700,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Dum Dum Metro",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-25",
      "BHK": 2,
      "Rent": 22000,
      "Size": 800,
      "Floor": "4 out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Hazra, Kalighat",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-27",
      "BHK": 2,
      "Rent": 6500,
      "Size": 450,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Ajoy Nagar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-31",
      "BHK": 2,
      "Rent": 8500,
      "Size": 550,
      "Floor": "2 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Kasba -East",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-03",
      "BHK": 2,
      "Rent": 18000,
      "Size": 800,
      "Floor": "Ground out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-27",
      "BHK": 2,
      "Rent": 12000,
      "Size": 550,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Baghajatin",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-15",
      "BHK": 1,
      "Rent": 9000,
      "Size": 600,
      "Floor": "2 out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-09",
      "BHK": 1,
      "Rent": 6000,
      "Size": 500,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "New Garia, Garia",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-28",
      "BHK": 2,
      "Rent": 20000,
      "Size": 1000,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Anandapur",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-23",
      "BHK": 1,
      "Rent": 5000,
      "Size": 300,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Dum Dum Metro",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-28",
      "BHK": 2,
      "Rent": 12000,
      "Size": 1200,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Boral",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-23",
      "BHK": 2,
      "Rent": 10000,
      "Size": 500,
      "Floor": "3 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Rabindra Pally, Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-29",
      "BHK": 4,
      "Rent": 18000,
      "Size": 1200,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Bagbazar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-13",
      "BHK": 2,
      "Rent": 15000,
      "Size": 900,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-13",
      "BHK": 3,
      "Rent": 22000,
      "Size": 1300,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 2",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 3,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-13",
      "BHK": 4,
      "Rent": 35000,
      "Size": 1600,
      "Floor": "1 out of 5",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 3",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 3,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 3,
      "Rent": 21000,
      "Size": 1450,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Ajoy Nagar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-06",
      "BHK": 2,
      "Rent": 25000,
      "Size": 1100,
      "Floor": "2 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Action Area 1, Rajarhat Newtown",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-16",
      "BHK": 2,
      "Rent": 180000,
      "Size": 950,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Avenue S, Santoshpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-06",
      "BHK": 1,
      "Rent": 6000,
      "Size": 600,
      "Floor": "8 out of 5",
      "Area Type": "Carpet Area",
      "Area Locality": "Pratiraksha Nagar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-04",
      "BHK": 2,
      "Rent": 14000,
      "Size": 700,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Kudghat, Ashok Nagar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-15",
      "BHK": 3,
      "Rent": 8000,
      "Size": 750,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Sakher Bazar, Purba Barisha",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-04",
      "BHK": 2,
      "Rent": 8000,
      "Size": 1000,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Purbasan, Thakurpukur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-25",
      "BHK": 1,
      "Rent": 6000,
      "Size": 220,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Bidhan Pally, Bansdroni",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-21",
      "BHK": 1,
      "Rent": 8000,
      "Size": 300,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Naktala, Garia",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-27",
      "BHK": 1,
      "Rent": 6000,
      "Size": 300,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Tiljala Road",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 1,
      "Rent": 20000,
      "Size": 700,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Sankaritola",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-06",
      "BHK": 3,
      "Rent": 12000,
      "Size": 800,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Parnashree Lake, Behala",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-28",
      "BHK": 3,
      "Rent": 15000,
      "Size": 1600,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Garia",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-15",
      "BHK": 2,
      "Rent": 14000,
      "Size": 1000,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Kasba",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-30",
      "BHK": 1,
      "Rent": 5000,
      "Size": 20,
      "Floor": "2 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Dakshineswar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-10",
      "BHK": 2,
      "Rent": 7000,
      "Size": 400,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "chatana",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-23",
      "BHK": 1,
      "Rent": 3900,
      "Size": 200,
      "Floor": "2 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Shyam Bazar",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-09",
      "BHK": 3,
      "Rent": 14000,
      "Size": 840,
      "Floor": "1 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Mukundapur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-19",
      "BHK": 1,
      "Rent": 6300,
      "Size": 300,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 5",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-07-03",
      "BHK": 2,
      "Rent": 13000,
      "Size": 550,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 5",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-07-03",
      "BHK": 1,
      "Rent": 6800,
      "Size": 300,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 5",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 2,
      "Rent": 8000,
      "Size": 800,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Behala Chowrasta",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 2,
      "Rent": 10000,
      "Size": 740,
      "Floor": "Ground out of 6",
      "Area Type": "Carpet Area",
      "Area Locality": "Sonarpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-25",
      "BHK": 2,
      "Rent": 18000,
      "Size": 1300,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Santoshpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-13",
      "BHK": 2,
      "Rent": 8000,
      "Size": 650,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Garia Station, Garia",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-06",
      "BHK": 2,
      "Rent": 8000,
      "Size": 490,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Entally",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-08",
      "BHK": 1,
      "Rent": 4700,
      "Size": 250,
      "Floor": "2 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Kaikhali",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-08",
      "BHK": 1,
      "Rent": 4700,
      "Size": 250,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Dash Drone, Rajarhat Newtown",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-06",
      "BHK": 1,
      "Rent": 4500,
      "Size": 450,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Rabindra Pally, Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-30",
      "BHK": 1,
      "Rent": 6000,
      "Size": 300,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-24",
      "BHK": 2,
      "Rent": 16000,
      "Size": 750,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Rajdanga Gardens, Kasba",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-01",
      "BHK": 1,
      "Rent": 4700,
      "Size": 250,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Kaikhali",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-17",
      "BHK": 2,
      "Rent": 14000,
      "Size": 751,
      "Floor": "3 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Baghajatin",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 2,
      "Rent": 9000,
      "Size": 900,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Lake Town",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-23",
      "BHK": 2,
      "Rent": 5000,
      "Size": 400,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-13",
      "BHK": 2,
      "Rent": 17500,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-06-11",
      "BHK": 2,
      "Rent": 8500,
      "Size": 1000,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "South Baksara",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-26",
      "BHK": 3,
      "Rent": 15000,
      "Size": 1500,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Chandannagar, Hooghly-Chinsurah",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-25",
      "BHK": 2,
      "Rent": 12500,
      "Size": 750,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Sukhpally, Haltu",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-11",
      "BHK": 1,
      "Rent": 13000,
      "Size": 1200,
      "Floor": "2 out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Kasba",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-06",
      "BHK": 2,
      "Rent": 8000,
      "Size": 700,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Sakher Bazar, Purba Barisha",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 2,
      "Rent": 8000,
      "Size": 700,
      "Floor": "4 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Garia Dhalua Nabapally",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-21",
      "BHK": 2,
      "Rent": 8000,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Chinar Park, Rajarhat",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-12",
      "BHK": 2,
      "Rent": 7000,
      "Size": 1200,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Konnagar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-05",
      "BHK": 2,
      "Rent": 2200,
      "Size": 550,
      "Floor": "2 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Behala silpara",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-25",
      "BHK": 2,
      "Rent": 8000,
      "Size": 800,
      "Floor": "Ground out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Vip Road",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-11",
      "BHK": 2,
      "Rent": 5500,
      "Size": 280,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "New Barrakpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-04",
      "BHK": 3,
      "Rent": 20000,
      "Size": 1100,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Thakurpukur, Kolkata",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 3,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 2,
      "Rent": 7000,
      "Size": 950,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Kaikhali",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-13",
      "BHK": 1,
      "Rent": 3500,
      "Size": 250,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Phool Bagan, Kankurgachi",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 2,
      "Rent": 5000,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Hindmotor",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-30",
      "BHK": 3,
      "Rent": 20000,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-27",
      "BHK": 2,
      "Rent": 7000,
      "Size": 650,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Howrah",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-08",
      "BHK": 2,
      "Rent": 10000,
      "Size": 700,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Benia Pukur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-15",
      "BHK": 2,
      "Rent": 7000,
      "Size": 700,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Baguiati",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-29",
      "BHK": 3,
      "Rent": 12000,
      "Size": 1000,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "E M Bypass",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-13",
      "BHK": 2,
      "Rent": 14500,
      "Size": 900,
      "Floor": "1 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Panchanan Tola, Thakurpukur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-25",
      "BHK": 1,
      "Rent": 6000,
      "Size": 700,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "VIP Nagar, E M Bypass",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-04",
      "BHK": 2,
      "Rent": 9500,
      "Size": 700,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Jadavpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-27",
      "BHK": 2,
      "Rent": 10000,
      "Size": 450,
      "Floor": "2 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Behala",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-06",
      "BHK": 1,
      "Rent": 3500,
      "Size": 120,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Dum Dum Cantonment",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-01",
      "BHK": 2,
      "Rent": 9000,
      "Size": 800,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "New Garia, Garia",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-07",
      "BHK": 3,
      "Rent": 40000,
      "Size": 1220,
      "Floor": "2 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 3",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-23",
      "BHK": 3,
      "Rent": 16500,
      "Size": 1100,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Mominpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-12",
      "BHK": 3,
      "Rent": 8000,
      "Size": 700,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Halisahar Station Road, Kanchrapara",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 2,
      "Rent": 12000,
      "Size": 800,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Santoshpur",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-27",
      "BHK": 2,
      "Rent": 6500,
      "Size": 670,
      "Floor": "2 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Dunlop, Dakshineswar, Belgharia Expressway",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-30",
      "BHK": 4,
      "Rent": 40000,
      "Size": 1300,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Ballygunge",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 3,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-06",
      "BHK": 1,
      "Rent": 5000,
      "Size": 190,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Baguihati",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-24",
      "BHK": 2,
      "Rent": 9000,
      "Size": 700,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Kabardanga",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-17",
      "BHK": 1,
      "Rent": 7000,
      "Size": 240,
      "Floor": "Ground out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Jadavpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-19",
      "BHK": 2,
      "Rent": 18000,
      "Size": 850,
      "Floor": "2 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "Behala Chowrasta",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-26",
      "BHK": 1,
      "Rent": 9000,
      "Size": 950,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Haltu",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-11",
      "BHK": 1,
      "Rent": 5500,
      "Size": 450,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Botanical Garden Area",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-08",
      "BHK": 2,
      "Rent": 7500,
      "Size": 800,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Bonhooghly",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-02",
      "BHK": 2,
      "Rent": 4000,
      "Size": 600,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Nilgung Old Bazar",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-30",
      "BHK": 3,
      "Rent": 10500,
      "Size": 800,
      "Floor": "2 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Teghoria, Baguiati",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-03",
      "BHK": 3,
      "Rent": 15000,
      "Size": 1100,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Survey Park",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-16",
      "BHK": 2,
      "Rent": 15000,
      "Size": 800,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Baguiati",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-13",
      "BHK": 1,
      "Rent": 50000,
      "Size": 2200,
      "Floor": "2 out of 5",
      "Area Type": "Super Area",
      "Area Locality": "Kanchrapara",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 3,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-08",
      "BHK": 2,
      "Rent": 12000,
      "Size": 950,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Jote Shibrampur, Joth Shibrampur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-25",
      "BHK": 2,
      "Rent": 11000,
      "Size": 550,
      "Floor": "2 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Ultadanga",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-04",
      "BHK": 2,
      "Rent": 12000,
      "Size": 1800,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Birati",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-11",
      "BHK": 2,
      "Rent": 8000,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Chinar Park, Rajarhat",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-27",
      "BHK": 2,
      "Rent": 18000,
      "Size": 600,
      "Floor": "Ground out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Bagha Jatin Pally",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-24",
      "BHK": 2,
      "Rent": 8000,
      "Size": 750,
      "Floor": "2 out of 4",
      "Area Type": "Carpet Area",
      "Area Locality": "rishi aurobindo sarani neat NIOH hospital",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-10",
      "BHK": 2,
      "Rent": 7000,
      "Size": 685,
      "Floor": "2 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Dum Dum Metro",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-24",
      "BHK": 1,
      "Rent": 6500,
      "Size": 44,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Baranagar",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-10",
      "BHK": 4,
      "Rent": 13000,
      "Size": 1200,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Tollygunge",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-05",
      "BHK": 2,
      "Rent": 9000,
      "Size": 500,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Airport Near Gate No. 21/2",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-29",
      "BHK": 4,
      "Rent": 10000,
      "Size": 1110,
      "Floor": "2 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Purbasa",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-05",
      "BHK": 2,
      "Rent": 12000,
      "Size": 1000,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Jadavpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-26",
      "BHK": 2,
      "Rent": 5000,
      "Size": 392,
      "Floor": "Ground out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Jadavpur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-09",
      "BHK": 2,
      "Rent": 6000,
      "Size": 700,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Barasat-Barrackpore Road",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-19",
      "BHK": 1,
      "Rent": 5200,
      "Size": 750,
      "Floor": "2 out of 4",
      "Area Type": "Super Area",
      "Area Locality": "Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-07",
      "BHK": 3,
      "Rent": 15000,
      "Size": 1500,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Biren Roy Road (W) Chowrashtra Behala, Raja Rammohan Roy Road",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-04-29",
      "BHK": 2,
      "Rent": 9000,
      "Size": 900,
      "Floor": "Ground out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Keshtopur",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 2,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-03",
      "BHK": 1,
      "Rent": 24000,
      "Size": 710,
      "Floor": "1 out of 1",
      "Area Type": "Super Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Agent"
    },
    {
      "Posted On": "2022-05-26",
      "BHK": 1,
      "Rent": 5500,
      "Size": 400,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "jadavpur central park east",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-24",
      "BHK": 1,
      "Rent": 10000,
      "Size": 700,
      "Floor": "1 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Garia",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-07-03",
      "BHK": 2,
      "Rent": 15000,
      "Size": 1000,
      "Floor": "Ground out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Tn Chatterjee Street",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-12",
      "BHK": 1,
      "Rent": 4700,
      "Size": 250,
      "Floor": "1 out of 2",
      "Area Type": "Super Area",
      "Area Locality": "Kaikhali",
      "City": "Kolkata",
      "Furnishing Status": "Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 1,
      "Rent": 5000,
      "Size": 500,
      "Floor": "Ground out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Bata Nagar",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-20",
      "BHK": 2,
      "Rent": 5000,
      "Size": 450,
      "Floor": "2 out of 2",
      "Area Type": "Carpet Area",
      "Area Locality": "Birati",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-27",
      "BHK": 3,
      "Rent": 15000,
      "Size": 1400,
      "Floor": "1 out of 3",
      "Area Type": "Super Area",
      "Area Locality": "Survey Park",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-05-14",
      "BHK": 1,
      "Rent": 5000,
      "Size": 500,
      "Floor": "1 out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Bata Nagar",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-17",
      "BHK": 2,
      "Rent": 6000,
      "Size": 700,
      "Floor": "Ground out of 1",
      "Area Type": "Carpet Area",
      "Area Locality": "Hatiara Extention",
      "City": "Kolkata",
      "Furnishing Status": "Unfurnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    },
    {
      "Posted On": "2022-06-04",
      "BHK": 3,
      "Rent": 18000,
      "Size": 1200,
      "Floor": "1 out of 3",
      "Area Type": "Carpet Area",
      "Area Locality": "Salt Lake City Sector 1",
      "City": "Kolkata",
      "Furnishing Status": "Semi-Furnished",
      "Tenant Preferred": "Bachelors/Family",
      "Bathroom": 1,
      "Point of Contact": "Contact Owner"
    }
];
